global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "pharmacy_web"
    static_configs:
      - targets: ["web:8000"]
    metrics_path: /metrics

  - job_name: "pharmacy_statsd"
    static_configs:
      - targets: ["statsd_exporter:9102"]
    metrics_path: /metrics
