global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "pharmacy_web"
    static_configs:
      - targets: ["web:8000"]
    metrics_path: /metrics

  - job_name: "pharmacy_celery"
    static_configs:
      - targets: ["celery_worker:9090"]
    metrics_path: /metrics
